### ISSUE TITLE
UFL list performance

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#225]
The performance of the archive review pages are very slow. This is mostly due to some innefficiencies in Django Rest Framework , inefficiencies in Django ORM and the sheer number of reviews.

I've already added some optimalisations for the first two, mostly in instructing Django ORM to fetch data more eagerly (normally related objects are fetched lazily, adding overhead). This managed to cut time spent on DB calls by as much as 50% (and also cutting the amount of DB queries from ~310 to ~130). Also, setting all fields to readonly in the DRF serializer also speeds up the serializer by 10%. (As this disables a lot unnecessary code). 

This helps, but still results in unsatisfactory performance. We have a few options to further enhance performance:

1) Further optimize the ORM. 130 DB queries is still a lot, and with some further ``select_related`` and ``prefetch_related`` calls we might shave off some more queries.
2) Optimize how we fetch data. Right now, we call A LOT of related objects which we barely need. (For example, we fetch latest_review to get it's ID, but this also pulls in a lot of other stuff we really don't need).
This can be optimized by either using RawSQL queries to fetch such data, or using Django ORM's annotation API.
3) Move paging from front-end to back-end. Right now we fetch all reviews and sent it to the front end, where we break it up in pages. This means we have to wait very long on first load, but we don't have to wait after. It also allows us to filter, sort and search client-side only. 
If we were to move the paging to the backend, we'd only have to fetch and serialize batches of at most 20 studies, which is a lot faster. However, this would require a lot of rewriting code, as we'd need to move search, sort and filters to the backend as well. (And would make setting up filters a lot more involved that it is currently).

Of all options, 3 is the best option performance wise (we'd probably need to measure response times in ms instead of seconds). But I'm hesitant because of the current implementation makes filtering so much easier. Additionally, this method would require us to actually return Querysets in the views (we now return lists which filters out duplicates). Which is an additional hurdle.

**Comment by tymees** [comment]
If we were to do option 3, I'd suggest actually making an additional implementation of UFL. As I had the forethought to setup UFL with clear seperation of tasks, we'd only need to write a new data controller class which offloads most the work to Django. 

This way, we can keep the dynamic filtering system for pages with fewer items to display, which is quite a bit easier to configure.

**Comment by miggol** [comment]
First off, great work on the optimizing the calls with selects and prefetches. I do like how currently loading everything locally makes filtering very snappy and not require server time. But at the same time, I think this is an approach that would rarely exist in the wild without some form of caching. At least not in our case, where database writes are few and far between. Would it be hard to keep the results of `reviews:my_archive` in localStorage? 

We would need to write an API call to get the latest DB version so UFL knows when to refresh everything. But even after a DB change we could display the old cached data while the new stuff is getting fetched, which would cover most navigation cases. Then we change the loading notification to "De gegevens worden ververst, dit kan even duren".

Sorry to add an option 4. Option 1 and 2 seem like steps we would get round to eventually anyway, regardless of approach. I'm down for option 3 as well if you prefer, I just don't want to throw out the beautiful UFL baby with the bathwater if browserside caching would be easy.

**Comment by tymees** [comment]
Hm, caching would work as a quick band-aid; However, I would suggest doing the caching in Django instead. For three main reasons: 1) it's faster to implement [(as it would only require adding a method decorator)](https://docs.djangoproject.com/en/dev/topics/cache/#the-per-view-cache) and 2) it would allow us to invalidate the cache for everyone if we deem it necessary.

**Comment by tymees** [comment]
I have also looked into option 3; it would certainly be possible (in fact I have basic functionality working already), but very restrictive compared to the current method. Searching would limited to a few types of fields, and ignore any of the get_x_display values. Additionally, filters would either be limited to ChoiceFields or would require lots of work to work with any kind of performance (and would again exclude the get_x_display fields or any non-DB fields).

**Comment by miggol** [comment]
Django caching is something we should probably be doing already. And it seems easy, so let's do it! Band-aid or not. From skimming the docs I'm assuming it would not support `MyDecisionsAPIView` which depends on user and group variables,

The more I think about it, a localStorage cache does look like it would bring some problems. Things like possible actions would not change before the cache was done updating, causing some confusion. Maybe relegating the current search and filtering to a separate "advanced search" page, and doing the rest of the sorting in Django for the pages that should be "quick" makes more sense.

**Comment by tymees** [comment]
Group variables aren't an issue (as those are path variables and those will be cached separately from each other). The user variables shouldn't cause an issue either, as there are options to have a cache for each user (https://docs.djangoproject.com/en/dev/topics/http/decorators/#django.views.decorators.vary.vary_on_cookie)

Having a separate 'advanced search' would probably result in the same issues as option 3 I think, as filtering only on db fields is kinda a Django limitation.

**Comment by miggol** [comment]
Ah yes, vary on cookie would be best to support the permissions mixins. With advanced search I mean the current UFL view, which loads the entire list locally. We would use option 3 for the "general" decisions list.

**Comment by tymees** [comment]
It seems to work excelently: https://github.com/UiL-OTS-labs/ethics/tree/feature/ufl-caching

I do think we should add some invalidation logic as well, such as when a new study is submitted and when someone reaches a dicision, so I'm not opening a PR for it just yet

**Comment by tymees** [comment]
This issue will be solved by migrating to UU-List; a new list view that was created with this problem in mind
