### ISSUE TITLE
Adjustments for preassessment / NWO proposals

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#256]
The preassessment route needs a good textual retouch, after the current devevelop/master cycle is done. Copying from the secretary request:

> Op https://fetc.hum.uu.nl/ de Startpagina:
> 
> voor voortoetsing t.b.v. subsidieaanvraag; > voor (al dan niet goedgekeurde) onderzoeksaanvragen
> 
> Op https://fetc.hum.uu.nl/proposals/start/pre/ (weer zo’n véél te lange tekst nu):
> 
> ONDERZOEKSAANVRAGEN
> 
>* Soms is bij het indienen van een aanvraag bij een subsidieverstrekker een ethische verklaring nodig.
>* Goedgekeurde NWO-aanvragen hebben ook een ethische verklaring nodig alvorens een startdatum vastgesteld kan worden.
> 
> In deze gevallen kunnen onderzoekers de FETC-GW verzoeken om de onderzoeksaanvraag te laten toetsen. Dit kan via deze route van de portal.
> 
> NB: De toetsing kan alleen op hoofdlijnen plaatsvinden en vervangt NIET de reguliere toetsing van specifieke studies; elke mensgebonden studie die in het kader van de onderzoeksaanvraag zal worden uitgevoerd dient vóóraf goedgekeurd te zijn door de FETC-GW.

**Comment by miggol** [comment]
Additionally, these kinds of studies should not appear in the semi-public archive when accepted by the committee.

**Comment by tymees** [comment]
Should not, or should not automatically? That wasn't entirely clear to me

**Comment by tymees** [comment]
@miggol is this still necessary? This issue is almost a year old
