### ISSUE TITLE
The success_url after making a decision should be the review details page

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#269]
As stated in title

**Comment by tymees** [comment]
In all cases, or just when a committee member makes a decision?

**Comment by miggol** [comment]
I'm thinking yes also for a secretary final decision, but not for a supervisor decision because that would result in a permission denied situation. Or am I forgetting something obvious?

There are a couple more success_urls we could change to be more consistent. Like ChangeChamberView and ReviewAssignView.

**Comment by tymees** [comment]
> I'm thinking yes also for a secretary final decision, but not for a supervisor decision because that would result in a permission denied situation. Or am I forgetting something obvious?

Hm yes that is what I was suggesting. I should've said 'all cases except supervisor decisions'. The ReviewDetailView isn't accessible for supervisors.

> There are a couple more success_urls we could change to be more consistent. Like ChangeChamberView and ReviewAssignView.

Good point, let's redirect them to the detail view as well!

**Comment by Meesch** [comment]
Addressed with PR #383
