### ISSUE TITLE
Add CSRF error page

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#294]
Currently when CSRF verification fails, one gets a (very) ugly Django error view. It would be better to provide a nice error page with some resolution options (like the current error views for 400/404/500/etc).

The trick would be how to explain people to do a fresh refresh instead of a normal reload (as a normal reload reloads the HTML, and thus the CSRF token, from the local cache).

**Comment by tymees** [comment]
See also https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-failure-view

**Comment by Meesch** [comment]
Check out: /Users/Stiph002/Projects/ethics/main/templates/error

**Comment by Meesch** [comment]
Closed with PR #356
