### ISSUE TITLE
[unconfirmed] "Datum goedkeuring" presented to submitter should refer to date_confirmed

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#326]
Currently it refers to `date_reviewed`, or at least it's incorrect according to secretary.

Sorry for the vague issue, this came up in a rushed team call and I'm heading out soon.

**Comment by tymees** [comment]
Thus, in technical terms, it should refer to ``date_confirmed``. This is going to be a _fun_ hunt in the code :P
