### ISSUE TITLE
[Bug] Asking for PDF of unfinished proposal can cause issues

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#337]
```
  File "./proposals/templatetags/proposal_filters.py", line 29, in necessity_required
    return check_necessity_required(study.proposal, age_groups, study.has_traits, study.legally_incapable)
  File "./studies/utils.py", line 40, in check_necessity_required
    result |= has_traits
TypeError: unsupported operand type(s) for |=: 'bool' and 'NoneType'
```

I'm working on it already, should be an easy fix. But we may want to remove the ability to generate a PDF of unfinished applications either way.

**Comment by miggol** [comment]
Although the bug is technically fixed, I think we should remove the generate PDF link for unfinished proposals. It opens many avenues of bugs and even abuse: some instituations might presume that a PDF constitutes proof of submission. Thoughts @tymees ?

**Comment by tymees** [comment]
I think it would be very reasonable to only get a PDF once you've submitted it, as it's meant as a 'final immutable representation' of that specific proposals anyway

**Comment by miggol** [comment]
The actual error is fixed, but I still need to remove the PDF option for unfinished proposals
