### ISSUE TITLE
Tag reviews as supervisor reviews properly

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#350]
Right now, we can distinguish committee reviews from supervisor reviews by it's `stage`. Supervisor reviews will always stay on that stage, even when they're concluded. 

That's counter intuitive, as you'd think they should reach a 'concluded' stage at some point. However, if one (accidentally) actually reaches that point the portal will treat it as a committee review. 

Thus, I think we should add a field to the Review model that explicitly states what kind of review it is. Maybe even increase the scope and try to sort out this whole review mess a bit, but it might be better to keep it small :P

Toughts @miggol @Meesch ?

**Comment by tymees** [comment]
Ideally I'd like a new field, as the whole point is to _easily_ differentiate the two. If we'd add new stages and start using those, it's going to be even _worse_ to find the correct set. For example, it's quite common atm to do something like this:
````python
reviews = Review.objects.filter(stage__gte=Review.COMMISSION)
````
to get a list of all reviews that are being reviewed or have advanced even further during the process. This is easy, as the stage field is a numeric field with every stage given a number (with higher numbers being 'later' in the process)

If we'd add more stages specifically for those two variants, we're going to need to do something like this to accomplish the same:
````python
reviews = Review.objects.filter(Q(stage=Review.COMMISSION) | Q(stage=Review.CLOSING) | Q(stage=Review.CLOSED))
````
Not really that elegant and not to mention very error-prone...

Alternatively, having a new field would result in something like this:
````python
reviews = Review.objects.filter(stage__gte=Review.COMMISSION, is_commission_review=True)
````
This is way more descriptive in my opinion, and way more fault tolerant

**Comment by tymees** [comment]
Oh also, this issue was sparked by a Review suddenly changing it's stage to ``Review.COMMISSION``, even though that should be impossible. So I don't think having different stages would really help in that regard :P

**Comment by Meesch** [comment]
Fair enough. Let's create a new field!

**Comment by miggol** [comment]
Somewhat related: if you're an application's supervisor and also a committee reviewer, you always get the supervisor decide view. Besides being a huge conflict of interest, this is of course a weird edge case. But reading this issue makes me realize why the decide view works that way at all. Indeed, there should be an unambiguous way to tell what kind of review you're dealing with.

**Comment by tymees** [comment]
Just adding a comment, to indicate urgency:

This is an enhancement, not a fix. We can already differentiate between the two types when needed, this issue only proposes a way to make it slightly easier to do. Thus, it has a very low priority
