### ISSUE TITLE
[RFC] Start page redesign

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#364]
So I was bored yesterday evening....

The current start page is.... not great. It's a wall of text, and not really laid out in a way to convey information _efficiently_. So, I've taken 30 minutes to throw this together.

![image](https://user-images.githubusercontent.com/7061963/179172200-d34fe13f-1bfa-4ec5-b736-511b47afc72c.png)
(Ignore header, nav and footer, obviously)

The main focus was on making the page easier to process at a glance and make information more 'focussed'. (Especially the new 'before you start' section. I think this layout will actually make people read it (more often)).

So obviously I've also condensed the amount of 'action' links to just 5 buttons. This has some implications:
- The gazillion 'my applications' page variants are now 1 button. So, we should also re-design those pages to work as a single page with (preset) filters.
- The 4 'create new proposal' pages are also now under one button. Obviously, this doesn't work atm, as the variants are _very_ different. Thus, I'd like to propose a new landing page where one fills in a basic form that routes them to the right form variant. 
  I think this will actually improve the current flow, as that new page can provide more information about the 4 variants. (And in the future, this page might be a great place to let users link their research portal 'entry' for this study, if they didn't come to the portal through the research portal)
- The archive pages probably should get the treatment as the 'my applications' page, combining them with filters.

One last thing:
I thought up some variations for the 'continue proposal' thingy:

![image](https://user-images.githubusercontent.com/7061963/179175033-f3e1410f-611a-4286-b889-b7e8ea40c7cf.png)

I would say there should one be one of them at any given time, with the following 'priority':
1. Any open supervisor reviews, ordered by date submitted ascendingly
2. The most recently editted draft proposal
3. The most recently submitted proposal still under review

If none comes up, the thingy doesn't show. The review takes priority in my eyes because supervisors 1) rarely have drafts of their own and 2) never seem to be able to find the review page without reading the email twice.

**Comment by tymees** [comment]
Two small notes:
- Obviously this needs some polish still, but it's a 30 minute mockup
- I really don't like the initial 2 paragraphs. It's not very welcoming. Still, that's something for the secretary/committees to decide...

So what do you guys think; any feedback? @miggol @Meesch 

Of course we should also discuss it with Desiree, but let's brainstorm internally first

**Comment by Meesch** [comment]
This all sounds like a really good idea: at a glance it strikes me that most of this can be done in the front-end, and I think that you are already at the core of a lot of usability issues with the portal. I say let's plan a session to sketch out how we want users (researchers, reviewers, etc) to navigate the portal and immediately discuss implementation options, maybe in August?

**Comment by djhcapel** [comment]
So Ty, your suggestion is to rewrite:
Formal approval by a chamber for the FEtC-H (by means of an official approval letter) is required for research involving human participants within the UU Faculty of Humanities. You must acquire this approval prior even to recruiting participants. Therefore, always wait for the letter of approval before starting research activities.

NB: Approved applications will appear in the archive of this portal. Anyone studying or working at the Faculty of Humanities with a Solis-ID can access this archive through the menu bar above. 

I will discuss this with the chairs.

**Comment by tymees** [comment]
There is no rush... This redesign is not planned until we have bandwidth to handle it. Which will be after some of the other portals are live
