### ISSUE TITLE
Fix email subjects formatting

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#365]
Some(all?) email subjects are missing a space between 'FEtC-H' and the chamber. In addition, the dutch version ('FETC-GW') be used. For example:

``FEtC-HLK-22-115-02`` should be: ``FETC-GW LK: 22-115-02``

**Comment by tymees** [comment]
@Meesch sounds like a good issue for you?

**Comment by miggol** [comment]
Nabbing this issue to quickly sneak it into the next master update

**Comment by miggol** [comment]
Fixed in master
