### ISSUE TITLE
New public archive

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#369]
Currently the public archive of studies is a manually maintained [page](https://fetc-gw.wp.hum.uu.nl/goedgekeurde-aanvragen/) on the FETC wordpress site; it might be easier for everyone involved to have a page in the portal that does this automatically.

Some questions still unanswered:
- Should there be time limits? (not older than 3 years for example)
- Is there a need to hide specific proposals from that page?

Code should be relatively easy, as we already have the 'site-export' page which now acts as a source for the WP page.

**Comment by djhcapel** [comment]
See mail Desiree of 8 September (also to chairs both Chambers with question about maximum duration embargo period).

**Comment by djhcapel** [comment]
A time limit might be a good idea; some applications concern complete research projects though, e.g. NWO approved projects. These often concern 4-year PhD trajectories, so perhaps we should set the time limit to 5 years?

**Comment by tymees** [comment]
> See mail Desiree of 8 September (also to chairs both Chambers with question about maximum duration embargo period).

I think the embargo is not directly relevant to this issue, as that is also concerning the semi-public archive (and this issue is about a public archive). I'll open a separate issue related to that

**Comment by tymees** [comment]
Ready in acceptation

**Comment by djhcapel** [comment]
There has been some discussion in the FETC-GW, and we think it is better if names of both applicants and researchers with final responsibility are hidden. Main reason is that in case of double-blind peer review the names of the researchers (then authors of the paper) cannot easily be found via our website. Could these two columns be hidden or deleted?

**Comment by tymees** [comment]
This is a new issue, re-using this one will make stuff confusing.

I've created a new one, closing this one again.
