### ISSUE TITLE
Meerdere sessies en/of meerdere taken

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#373]
In de portal staat nu: Voor elke sessie stellen we in de komende schermen steeds dezelfde vragen. 
en: Voor elke taak stellen we in de komende schermen steeds dezelfde vragen.

Dit is verschrikkelijk onhandig, omdat in de meeste gevallen die ik ben tegengekomen, de sessies en/of de taken gelijk zijn aan elkaar. Je krijgt dus onnodige herhaling van informatie die een aanvraag compleet onoverzichtelijk maakt (ik heb wel eens een aanvraag voor een onderzoek met 7 identieke taken gehad: een enorm lang aanvraagformulier werd dat). Kunnen we dit niet veranderen, zodat men kan aangeven dat er 5 sessies/taken zijn die allemaal hetzelfde zijn? Of, iets ingewikkelder, 6 sessies/taken waarvan er steeds 3 precies hetzelfde zijn? 

Bijvoorbeeld: Bij meer dan één: Zijn deze sessies/taken exact hetzelfde? ja: één keer laten invullen, nee, meerdere keren laten invullen. Hoe dat moet als er 3x2 identieke sessies/taken zijn weet ik niet; hebben jullie een idee?

**Comment by miggol** [comment]
De huidige opstelling is inderdaad erg gebruiksonvriendelijk. Mijn voorkeur gaat uit naar het volgende:

- We vragen niet meer van tevoren hoeveel sessies een traject heeft.
- Bij de gegevens over een sessie nemen we een extra vraag op: "Hoe vaak wordt deze sessie binnen dit traject herhaald?" (oid)
- Na het aanmaken van één sessie kan je nog een sessie aanmaken, of door naar het volgende traject.
- De indiener kan zo veel sessies toevoegen als deze wil.
- Voordat de indiener doorgaat naar het volgende traject doen we nog een check: "Klopt het dat deelnemers in dit traject X aantal sessies doorlopen?" Voor het geval ze verkeerd gerekend hebben.

Precies hetzelfde systeem kan ook voor de taken binnen een sessie ingezet worden. Zo hoef je ook niet uit te vragen welke taken identiek zijn aan welke anderen.

**Comment by djhcapel** [comment]
O, lijkt me een hele verbetering!

**Comment by EdoStorm96** [comment]
I am looking at this again, and have a slightly different solution, which I think can be implemented easily. We keep the question about how many sessions there will be at the beginning, but change it to ask how many **unique** sessions there will be. This will need to be thoroughly explained of course. Then create a session for each unique session.

Then for each session, we add a field asking how many times this session will be repeated. This will make the routing of the process more streamlined in my opinion, as we don't need to create a split path, of create a new session, or continue.

Then at the end we do check if the total number is correct, as Michael suggested. Same for tasks.

**Comment by EdoStorm96** [comment]
Also, I am wondering, does the order of sessions and tasks in the application matter? Let's say someone wants to do two types of session, A & B. They want to do session A twice, then perform session B once, and then perform session A again. Should this be reflected in the application? Or can the application just say, in this case: 
- Session A: gets performed 3 times; 
- Session B: gets performed once.

**Comment by miggol** [comment]
> I am looking at this again, and have a slightly different solution, which I think can be implemented easily. We keep the question about how many sessions there will be at the beginning, but change it to ask how many unique sessions there will be. This will need to be thoroughly explained of course. Then create a session for each unique session.

I see how this would be less work, as we could reuse much of what is already in place. But I personally don't like the existing code. As it stands, session and task objects have to be created (or deleted!) behind the scenes in advance when submitting the the number of sessions. This creates additional interdependencies and makes it very hard to, for example, remove a specific session or task. Reducing the number given at the start just cuts off the last objects in the list IIRC.

So although there would be less reuse, I'm still in favour of just using a CreateView for each session or task you want to add. I think this would be more maintainable and slightly more user-friendly.

> Also, I am wondering, does the order of sessions and tasks in the application matter? 

No, as far as I know the FETC is mainly interested in the total time and effort investment of the participant. So precise ordering can be sacrificed here. Although if you like, a simple "order" field on the session can be added for little cost.
