### ISSUE TITLE
Student - more information on study

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#380]
Since a new policy will be in place for human-subject-related research by students as of 1 Sept 2022, I would like to be able to report over 2022-2023 (and the years to come):
- the number of students applying for approval by the FEtC-H
- what level they are (Ba, Ma, RMa)
- what study they do
- whether it concerns thesis research, an internship or anything else (please describe).
Now we only know e.g. 'als student in een Research Masterprogramma of -cursus'.

**Comment by tymees** [comment]
I would say these are two different but related issues. The first part is the new required fields:

> * what level they are (Ba, Ma, RMa)
> 
> * what study they do
> 
> * whether it concerns thesis research, an internship or anything else (please describe).
>   Now we only know e.g. 'als student in een Research Masterprogramma of -cursus'.

These seem straightforward; just two extra fields. 

I assume you want the thesis/internship/etc to be a multiselect with an 'other' field?

> * the number of students applying for approval by the FEtC-H

I would love to park this part in the ongoing statistics issue #118 as we agreed to discuss that in the coming months.

**Comment by djhcapel** [comment]
It concerns three fields, right?
> > * what level they are (Ba, Ma, RMa)
> > * what study they do
> > * whether it concerns thesis research, an internship or anything else (please describe):  indeed, a multiselect with an 'other' field.
 
> > * the number of students applying for approval by the FEtC-H
> 
> I would love to park this part in the ongoing statistics issue #118 as we agreed to discuss that in the coming months.

Okay (just in advance: I do not want to report just the numbers, but also include studies, # internships etc.).

**Comment by tymees** [comment]
> It concerns three fields, right?

We already ask for BA/MA/RMA, so that one doesn't need to be added

![image](https://user-images.githubusercontent.com/7061963/184844759-8f4f2f8c-5abe-4987-85af-59ac84e161a8.png)

**Comment by djhcapel** [comment]
Could we add a (free text) field to indicate the reason for assessment by the FEtC? As of this academic year (2022-2023) student research is, in principle, not assessed by the FETC.

**Comment by Meesch** [comment]
I would like to close this issue with PR #396, and then add Desiree's question about a free text field for students to explain why their research needs to be approved to a new issue, because all the original parts of the issue have been solved.
