### ISSUE TITLE
Add textual changes for regulation changes

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#381]
See mail from 28/7;

Some changes might be more involved

**Comment by djhcapel** [comment]
Yesterday I noticed that the Start page of the portal contains the text:

The regulations of the [General Chamber](https://fetc-gw.wp.hum.uu.nl/en/regulations-general-chamber-2/) or those of the [Linguistics Chamber](https://fetc-gw.wp.hum.uu.nl/en/regulations-linguistics-chamber/).

The two links do not work anymore. Could this also be adjusted to:

The regulations of the [FEtC-H] (https://fetc-gw.wp.hum.uu.nl/en/regulations-fetc-h/)
