### ISSUE TITLE
Update Self-Assesment Field for Linguistics Chamber

### ISSUE THREAD

**Issue by Meesch** [DH-IT-Portal-Development/ethics#382]
Per request of the secretary we have to think about how we want to present the ethical self-assesment field to the linguistics chamber, for whom this question is often not relevant. We can either make the question not obligatory, change the phrasing, or we can remove it altogether for the linguistics chamber.

**Comment by djhcapel** [comment]
Ik zou het bij nader inzien maar gewoon laten staan, dan blijft de portal ook gelijk voor AK en LK.

**Comment by Meesch** [comment]
Following the request of the secretary, we are keeping this field, as it will be good for linguists to consider ethical issues as well.
