### ISSUE TITLE
Criteria 'lange route' change with new regulations

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#393]
See also issue #390.

I just realized that the criteria for 'lange route' have also changed:

a.	if there is a hierarchical relationship between the researcher(s) and participant(s).; 
b.	if participants belong to a potentially vulnerable group;.
c.	if special categories of personal data are collected;.
d.	if the researcher states that (or has doubts whether) the research might, in part or in its entirety , involve such a burden that it could give rise to questions despite the informed consent obtained;.
e.	the total duration of the tasks in the session, excluding breaks and other non-task elements, exceeds the targeted maximum for the age group concerned (see table):
0–3 years old | 20 minutes
4–5 years old | 40 minutes
6–11 years old | 60 minutes
12–17 years old | 90 minutes
18–69 years   old | 120 minutes
70 and above | 60 minutes

f.	the researcher states that the risks of psychological, physical or other harm owing to participation in the research are (or that he or she has doubts whether those risks might be) more than minimal;.
g.	if the research uses deception.

For instance 'in other setting' is no longer a reason for 'lange route'.

**Comment by Meesch** [comment]
Vaak is de code 'te sensitive', en raadt nu vaak een lange route aan waar dat niet nodig is
