### ISSUE TITLE
Self assessment length limits

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#397]
So someone decided to write a whole essay for their self assessment, which is obviously not going to fit inside 500 characters.

While I have some things to say about researchers really needing to learn to write succinctly, I will admit 500 characters is too few.

We could just remove the limit altogether, but that carries a small risk we'd have to take into account. The proposal PDF generation really does not like table cells that span over more than 2 A4 pages. (Read: it crashes).  This was discovered when someone added their 1000 word entire reasearch proposal into the comments field at the end. 

I solved it by simply not rendering that field in a table, just at the root of the document. 

Another way would be to set a different limit, but I can not really think of a limit that's high enough for users but small enough to avoid the problem described above.

**Comment by miggol** [comment]
> I solved it by simply not rendering that field in a table, just at the root of the document.

Does this mean that the PDF issue is avoidable? 2000 characters seems fair to me, if we can get the PDF to render.

**Comment by tymees** [comment]
Yes it should be (just look at how the comments at the end of the PDF are done, that should work). I brought it up because we need to do that as well with a increase of the limit. Although, in hindsight I could've been more clear and succinct (ironically enough) about it :P

**Comment by miggol** [comment]
Okay good to know! Also, it might be worth testing if the bug still exists, because I think we moved from an unmaintaned easy_pdf to directly calling a way more recent version of xhtm2pdf since. You never know!

**Comment by tymees** [comment]
From e-mail: we should limit this field to 300 words or so

**Comment by Meesch** [comment]
Makkelijk te fiksen als we onze word-number validator gebruiken (wordt al gebruikt voor de description op de eerste pagina)

**Comment by djhcapel** [comment]
Wat is het maximum dat mogelijk is zonder pdf- of andere problemen? We willen bijv. bij voortoetsing niet meer de hele projectaanvraag hoeven door te nemen, maar we willen af kunnen gaan op de ethische reflectie van de onderzoeker.

**Comment by tymees** [comment]
Onbeperkt in principe, we kunnen namelijk om alle problemen (voor zover dat ze er (nog) zijn) wel heen werken.

Echter, ik zou afraden om geen maximum te hebben; je wilt immers niet 10 kantjes moeten beoordelen ;)
