### ISSUE TITLE
Rename the applicants field to 'betrokkenen'

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#398]
From e-mail:

>  Are any others researchers involved affiliated with ICON, OFR etc…? à ik doe als post-doc onderzoek binnen het project ANONYMOUS PROJECT van JOHN DOE. Als PI van het project is JOHN DOE ‘involved’, maar ik ben de enige uitvoerende onderzoeker van mijn eigen deelproject. Moet ik hier ja of nee aanklikken? Als ik ja klik, kan ik JOHN niet selecteren, bovendien verandert de vraag dan in ‘researchers carrying out the study’, dus dat is wat verwarrend.

**Comment by tymees** [comment]
I don't actually understand what needs to be changed when looking at the current text. (Funny, considering I created this issue)

**Comment by djhcapel** [comment]
I don't understand this issue either. I cannot find the email Ty is referring to either. Shall we just close this issue?
