### ISSUE TITLE
Talen informed consent documenten

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#401]
Kan er op de pagina waarin informed consent documenten ingediend worden de volgende vraag toegevoegd worden:

De documenten voor deelnemers zijn/worden vertaald in de volgende taal/talen: ........... / n.v.t.”

Dit is met name van belang als er onderzoek met anderstaligen of in andere landen wordt gedaan. Soms staat dat niet duidelijk in de aanvraag vermeld en soms horen we het pas achteraf. Dit maakt e.e.a. meteen duidelijk.

**Comment by djhcapel** [comment]
Ik zie dat ik nadere tekstuitleg moest geven:

"De documenten voor deelnemers zijn/worden vertaald in de volgende taal/talen: ........... / n.v.t.

Als de documenten in andere talen dan Nederlands of Engels moeten worden opgesteld, dan hoeven deze niet direct te worden ingediend. Het is wel noodzakelijk te vermelden dat deze vertaald zullen gaan worden. Bij goedkeuring moeten de documenten in andere talen wel worden aangeleverd, omdat de portal ook dient als officieel archief van goedgekeurde aanvragen. Dit kan eventueel na goedkeuring, maar kan ook bij een minimale revisie."

**Comment by miggol** [comment]
Example implementation:

A checkbox on the Documents screen which states "The consent and information documents will be translated to native language of the participants other than Dutch or English" (default off)

When checked, the text provided by Desiree appears.

**Comment by EdoStorm96** [comment]
Desiree, it would be quite difficult to add this on the same page. We now have added a new page, directly after the documents page. This is now a dropdown menu of the documents bubble in the navigation bar. Would this be satisfactory?
