### ISSUE TITLE
Direct users stuck before login to some kind of support

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#408]
Currently, the support and secretary email addresses are only visible once logged in. That's not very helpful for people who have trouble logging in, or are confused about for whom this portal is (e.g. lost FSW students). Same with researchers that need to be added to the HUM-LDAP.

We could add support contact info to the footer or FAQ pages. I don't know if there are spam / abuse reasons not to do so. We could also add the portal support email address to the FETC WP site.

**Comment by tymees** [comment]
Adding it to the footer is a nice long-term solution. However, this will only be possible with the move to DSC3.

I'm not so sure about the FAQ pages, as I don't think people use it atm. However, it doesn't hurt.

There is some spam concerns, but seeing as a lot of our emails are public and we don't really see that much spam therel I think the spamfilter works well enough. Just to be sure tho, we might want to do some JS tricks to make it a bit harder.

For the time being, I'd say just adding it to the login screen and non-logged-in index might be a good stop-gap
