### ISSUE TITLE
Elders goedgekeurde studies - reglement info klopt niet meer

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#410]
https://fetc.hum.uu.nl/proposals/start/pre_approved/

- NL is nu:

Deze kan je vinden op de UU-webpagina van de FETC-GW: [reglement Algemene Kamer (AK)](http://fetc-gw.wp.hum.uu.nl/reglement-algemene-kamer/) en [reglement Linguïstiek Kamer (LK)](http://fetc-gw.wp.hum.uu.nl/reglement-linguistiek-kamer/). Je kan jezelf en de commissieleden veel tijd besparen door je eerst goed te informeren.

Gebruik bij het invullen s.v.p. geen afkortingen waar de FETC-GW wellicht niet mee bekend is. Raadpleeg bij vragen eerst het reglement van de[ Algemene Kamer (AK)](http://fetc-gw.wp.hum.uu.nl/reglement-algemene-kamer/) of de [Linguïstiek Kamer (LK)](http://fetc-gw.wp.hum.uu.nl/reglement-linguistiek-kamer/), en neem eventueel daarna contact op met de secretaris (Desiree Capel, [fetc-gw@uu.nl](mailto:fetc-gw@uu.nl)).

- NL moet worden:

Dit reglement (https://fetc-gw.wp.hum.uu.nl/reglement-fetc-gw/) kan je vinden op de UU-webpagina van de FETC-GW. Je kan jezelf en de commissieleden veel tijd besparen door je eerst goed te informeren.

Gebruik bij het invullen s.v.p. geen afkortingen waar de FETC-GW wellicht niet mee bekend is. Raadpleeg bij vragen eerst het reglement(https://fetc-gw.wp.hum.uu.nl/reglement-fetc-gw/), en neem eventueel daarna contact op met de secretaris (Desiree Capel, [fetc-gw@uu.nl](mailto:fetc-gw@uu.nl)).

- EN is nu:

Please refer to the FEtC-H website for the regulations of [the General Chamber](https://fetc-gw.wp.hum.uu.nl/en/regulations-general-chamber-2/) and [the Linguistics Chamber](https://fetc-gw.wp.hum.uu.nl/en/regulations-linguistics-chamber/). You can save yourself and the committee members a great deal of time by making sure you are properly informed.

When filling in the forms please avoid using abbreviations the FEtC-Hmight not be familiar with.If you have questions, first consult the regulations of the [General Chamber](https://fetc-gw.wp.hum.uu.nl/en/regulations-general-chamber-2/) or the [Linguistics Chamber](https://fetc-gw.wp.hum.uu.nl/en/regulations-linguistics-chamber/),and if necessary contact the secretary (Desiree Capel,[fetc-gw@uu.nl](mailto:fetc-gw@uu.nl)).

- EN moet worden (ook spaties toevoegen waar die hadden moeten staan):

Please refer to the FEtC-H website for the regulations(https://fetc-gw.wp.hum.uu.nl/en/regulations-fetc-h/). You can save yourself and the committee members a great deal of time by making sure you are properly informed.

When filling in the forms please avoid using abbreviations the FEtC-H might not be familiar with. If you have questions, first consult the regulations(https://fetc-gw.wp.hum.uu.nl/en/regulations-fetc-h/),and if necessary contact the secretary (Desiree Capel,[fetc-gw@uu.nl](mailto:fetc-gw@uu.nl)).

**Comment by miggol** [comment]
Already approved applications should also send along their IC and info documents. They can do this by mail, and instructions to do this have to be added as part of this issue.
