### ISSUE TITLE
Feedback functionality; still needed?

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#430]
Is anyone ever using the feedback module?

Do people even know it exists?

**Comment by djhcapel** [comment]
I don't know this module. Feedback on what to whom?

**Comment by tymees** [comment]
This one:

https://fetc.hum.uu.nl/feedback/create/

It's just a textbox that saves a message in the DB, which no-one checks except me. But I think this answers my question 'Do people even know it exists?' with a resounding 'no'.

**Comment by djhcapel** [comment]
Perhaps no one checks the 'Help'....

**Comment by tymees** [comment]
Is going gonzo!
