### ISSUE TITLE
New text automatic emails new applications short/long route and revised applications

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#433]
**Tekst automatische mail bij nieuwe aanvraag, lange route:**

NL:

Beste collega,

Je aanmelding is door de FETC-GW ontvangen. De automatische screening van de portal heeft op basis van de door jou gegeven beschrijving voorlopig de status 'lange-route onderzoek', zie [appendix A van het reglement](https://fetc-gw.wp.hum.uu.nl/reglement-fetc-gw/) voor de criteria.

Dit houdt in dat je aanvraag op de eerstvolgende vergadering van de FETC-GW zal worden besproken, wanneer je aanvraag tenminste een week voor die vergadering is ingediend. Zie [de FETC-GW-agenda](https://fetc-gw.wp.hum.uu.nl/category/agenda/) voor een overzicht van de komende vergaderingen. Kort na de vergadering zul je de beoordeling ontvangen.

Met de vriendelijke groeten, namens de FETC-GW,

Desiree Capel, secretaris

Dit is een automatisch gegenereerd bericht.

EN:

Dear colleague,

The FEtC-H has received your application. The automatic screening of the portal has given your study the status of long-route research, see [appendix A in the regulations](https://fetc-gw.wp.hum.uu.nl/en/regulations-fetc-h/) for the criteria.

This means that your study will be discussed during the next FEtC-H meeting, if your application was submitted at least one week before that meeting. See [the FEtC-H agenda](https://fetc-gw.wp.hum.uu.nl/en/category/agenda-en/) for an overview of upcoming meetings. You will receive the assessment shortly after the meeting.

Met vriendelijke groet, on behalf of the FEtC-H,

Desiree Capel, secretary

This message was generated automatically.

**Tekst automatische mail bij nieuwe aanvraag, korte route:**

NL:

Beste collega,

Je aanmelding is door de FETC-GW ontvangen. De automatische screening van de portal heeft op basis van de door jou gegeven beschrijving voorlopig de status 'korte-route onderzoek' gekregen.

Dit houdt in dat wij ernaar streven om je binnen twee werkweken een eerste beoordeling van de FETC-GW te sturen.

NB: Het is mogelijk dat je aanvraag alsnog als 'lange-route onderzoek' wordt aangemerkt, in welk geval de beoordeling langer kan duren, zie het [reglement](https://fetc-gw.wp.hum.uu.nl/reglement-fetc-gw/). 

Met de vriendelijke groeten, namens de FETC-GW

Desiree Capel, secretaris

Dit is een automatisch gegenereerd bericht.

EN:

Dear colleague,

The FEtC-H has received your application. The automatic screening of the portal has given your study the status of 'short-route research'.

This means that we aim to send you an initial assessment of the FETC-GW within two working weeks.

Note: It is possible that your application may still be classified as a 'long-route research', in which case the asssessment procedure may take longer, see the [regulations](https://fetc-gw.wp.hum.uu.nl/en/regulations-fetc-h/)

Met vriendelijke groet, on behalf of the FEtC-H,

Desiree Capel, secretary

This message was generated automatically.

**Tekst automatische mail bij gereviseerde aanvraag:**

NL:

Beste collega,

Je gereviseerde aanvraag is door de FETC-GW ontvangen. 

Dit houdt in dat je revisie nu door twee leden van de FETC-GW zal worden beoordeeld; een eenvoudige revisie wordt alleen door de secretaris beoordeeld. We hopen je binnenkort een beoordeling te kunnen sturen.

Met de vriendelijke groeten, namens de FETC-GW

Desiree Capel, secretaris

Dit is een automatisch gegenereerd bericht.

EN:

Dear colleague,

The FEtC-H has received your revised application.

This means that your study will be assessed by two members of the FEtC-H; minor revisions will be assessed by the secretary only. We hope to be able to send you a review soon. 

Met vriendelijke groet, on behalf of the FEtC-H,

Desiree Capel, secretary

This message was generated automatically.

**Comment by djhcapel** [comment]
korte route: punt vergeten achter 'regulations'.

**Comment by miggol** [comment]
These are in acceptation now!
