### ISSUE TITLE
Make "definitive" PDF at time of approval

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#446]
Previously, PDFs were generated somewhat haphazardly. Since we moved to always generating them on the fly, proposal PDFs no longer serve an archival purpose unless manually downloaded at time of approval.

The main issue with this is that the PDFs will of course break with future updates. My suggestion is to create a new archival PDF filefield that gets populated by the PDF generator at time of approval. We can then choose to serve this PDF from that point onwards. Basically, we're coming full circle.

 I expect to be taking this one on and will assign myself once I actually start working on it.

**Comment by tymees** [comment]
> miggol assigned miggol and unassigned miggol 4 days ago

nice

--

Jup, seems like our decision to switch to on-the-fly generation was the incorrect option when looking at this problem.  In hindsight it would make our jobs a lot easier if we didn't have to think about backwards compatibility of the PDF _that much_. In addition, I think having a canonical hard copy of the  proposal when approved is also preferred from a more formal/non-technical standpoint.

So if I'm understanding your proposal correctly you want to add a second FileField that populates at the time of approval? (The other one being at the time of submission).

At that point I'd rather have something that _actually_ tracks different versions in a single mechanism. (As the PDF can change more than 2 times, for example when the secretary changes the documents after approval). 

[shameless self promotion] Actually this sounds like a perfect job for my TrackedFileField, which does exactly that! Tracking versions of the same file! [/shameless self promotion] The downside being that that's only in DSC 3.x


This issue also touches on a similar problem related to proposal diffing, but maybe we should leave that for now...

**Comment by miggol** [comment]
Done in prod!
