### ISSUE TITLE
Title portal - more explicit that it is the Faculty of Humanities

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#450]
I recently received two emails of people complaining they could not log into our portal, but neither of them was not associated with the Faculty of Humanities. The title of the homepage of the portal now only reads 'FETC-GW' and 'FETC-H'. Perhaps add: (Faculteit Geesteswetenschappen) and: (Faculty of Humanities)?

**Comment by tymees** [comment]
This is identical to issue #399 

Going to bump that issue instead, and close this one
