### ISSUE TITLE
UIL OTS > ILS

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#454]
*General information about the application:*
- To which research institute are you affiliated? one of the options should refer to Institute for Language Sciences (ILS) (replacing UiL OTS)
- How is this study funded? direct government funding: replace UiL OTS by ILS
*Participants*
- UiL OTS database > ILS database (adult and/or infant participants)
*Intervention study*
- Specify where the data collection will take place: replace UiL OTS Labs by ILS Labs (including the Babylab)
*Observational study*
- Specify where the data collection will take place: replace UiL OTS Labs by ILS Labs (including the Babylab)
*Task-based research and interviews*
- Specify where the data collection will take place: replace UiL OTS Labs by ILS Labs (including the Babylab)

**Comment by miggol** [comment]
UiL-OTS still appears in two places:

* The fixtures for institutions and such
