### ISSUE TITLE
Revisie/amendement

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#485]
Under Details, it now says 'revisie/amendement' for any revision or amendment. It would be really helpful if this would be either 'revision' or 'amendment'. Now I need to dive deeper into the application to find out what it is.

**Comment by tymees** [comment]
Some technical stuff for the person implementing this:

Technically amendments and revisions aren't tracked separately. (It's the same boolean). Thus, actually figuring out what kind it is is not that straightforward. ``Proposal.type()`` already has the correct check, but that method returns more than just revision/amendment. So I'd recommend refactoring that method by extracting the checks for revision/amendment into their own methods. That way we can use those new methods in the view to solve this issue, and we don't have duplicate code.
