### ISSUE TITLE
Privacy officer consulted? yes/no

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#491]
On the Data Management page, applicants are required to tick a box "Ik heb kennis genomen van het bovenstaande en begrijp mijn verantwoordelijkheden ten opzichte van de AVG.". Now that more and more people first discuss their study with the privacy officers (and data manager), I would like to change this to the following question, and instead of a tick box, a radio button yes/no:

"Ik heb mijn aanvraag en de documenten voor deelnemers besproken met de privacy officer. O ja O nee"

It will then be easier for me to check whether any correspondence about such study has been sent to the fetc-gw mailbox.

**Comment by miggol** [comment]
The question will no longer be required to proceed.

**Comment by djhcapel** [comment]
Question: where would I be able to see the response to this question?
Could it be incorporated in the pdf?
