### ISSUE TITLE
UFL search does not (always) search through all values in lists

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#500]
In the labman mailbox, a request for equipment was made and I did not recognize the name, so I was wondering whether approval had been given for this study. Searching for this person's name in 'all applications ever submitted' did not result in any hits. 

I called this person, and then it appeared (s)he was mentioned as 'Uitvoerende(n) (inclusief uzelf)' in the application. Could the search option be adjusted so that I can also find names of people added as 'Uitvoerende(n) (inclusief uzelf)'?

**Comment by tymees** [comment]
Ah, it's a bug in the search code; only the first item (applicant) of the list of applicants is evaluated. Sigh...

I'll attach it to the DSC project, it needs to be fixed there...

**Comment by tymees** [comment]
This issue will be solved by migrating to UU-List; (#557) a new list view that was created with this problem in mind
