### ISSUE TITLE
Workload members FEtC-H

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#502]
I now keep track of the number of revisions/short routes that I assign to a particular FEtC-H member in an Excel file in order to spread the workload more or less evenly over the members of a chamber. This is, however, not 100% correct, I do not receive warnings etc. 

Would it be possible for the secretary to see, in an overview, the applications that each member of a chamber is currently assessing? This would help me in deciding whom I can link to a new application / revision.

**Comment by miggol** [comment]
This could be done somewhat easily. For example, a separate page (linked on the assign view) which lists all members of AK and LK and the amount of reviews currently assigned to them.

It would also be nice to see what committee members have done in the past, for example amount of decisions in past 1/3/6 months.
