### ISSUE TITLE
Non-humanities users

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#509]
I've confirmed that IAM can give us a user's faculty with the SAML login data (as the `uuLegacyDepartment` attribute). So, we can use that to  validate if a user is from GW.

As some people seem to miss the giant 'GW' everywhere on the landing page, I do think it would be a good idea to use that information. The question is how;

I see two main options:

- Block all non-GW users on the application side, but use an allowlist to make sure those who need access can request them.
- Just display a warning to non-GW users as a banner on the frontpage. (In red to mark urgency)

There are probably others...

The first would be a very effective solution; however, it is also the hardest to implement. (And it will require all currently manually added to re-request access). In addition, it would cause a bit more work for support... A bit. The second is easiest, but can also be missed...

I'm for option 2, as non-GW users will also be effectively blocked from progressing on the first page of an application. (The first question is 'what institution are you from', so non-GW users will probably catch the problem there). However, I do want to ask the secretary first. 

Paging @djhcapel

**Comment by djhcapel** [comment]
Do you happen to know if all non-GW-ers trying to log in were Dutch or English-speaking? I just noticed on the EN landing page, it says: Faculty Ethics Assessment Committee – Humanities (with hyphen), whereas on the NE landing page is says: Facultaire Ethische Toetsingscommissie Geesteswetenschappen (without hyphen). Perhaps a hyphen in Dutch will help getting the focus on 'GW'?

I do not so much like red flags for just those who arrived at the wrong page, distracting those who did arrive at the right page.

Why not add something to the institute question saying "If you do not work or study at the Faculty of Humanities, we would like to refer you to the ethical assessment committee of your faculty."

**Comment by tymees** [comment]
> Do you happen to know if all non-GW-ers trying to log in were Dutch or English-speaking? 

It's a mix of both honestly. 

> Perhaps a hyphen in Dutch will help getting the focus on 'GW'?

Couldn't hurt, but honestly I doubt it will help that much...

> I do not so much like red flags for just those who arrived at the wrong page, distracting those who did arrive at the right page.

It would only be for users whose account does not belong to GW, so I don't see how it would be distracting?
But yes, maybe 'red' is a bit too harsh, an orange 'warning' might be better?

> Why not add something to the institute question saying "If you do not work or study at the Faculty of Humanities, we would like to refer you to the ethical assessment committee of your faculty."

Could work also

**Comment by djhcapel** [comment]
So only non-GW-ers would see the orange flag?? Then it seems fine to me. Plus the extra info at the institute question. See if those two things work?

**Comment by tymees** [comment]
Another concern raised over e-mail:
The users-only archive is also open to all; this might need to be limited as well. 

The discussion is currently ongoing, this issue is on hold till we know what to do with it.

**Comment by tymees** [comment]
Some feedback on the text itself would be greatly appreciated @djhcapel 

The version for when we don't know the faculty of the user:
![image](https://github.com/DH-IT-Portal-Development/ethics/assets/7061963/7a088ba4-f917-4800-b9b1-662864edeb58)

The version for when we do know it:
![image](https://github.com/DH-IT-Portal-Development/ethics/assets/7061963/1ad30f97-b8ce-4f7f-9873-0a60a9e1fdb0)

**Comment by djhcapel** [comment]
The version for when we don't know the faculty of the user:

Deze portal is bedoeld voor medewerkers (en studenten) van de Faculteit Geesteswetenschappen. Volgens onze gegevens werk/studeer je bij een andere faculteit of dienst. Controleer of je inderdaad een aanvraag wilt indienen bij de Facultaire Ethische Toetsingscommissie van Geesteswetenschappen.

Als je vermoedt dat er iets niet klopt, neem dan contact op met portalsupport.gw@uu.nl.

The version for when we do know it (and how do we know someone is affiliated to FSW??):

Deze portal is bedoeld voor medewerkers (en studenten) van de Faculteit Geesteswetenschappen. Volgens onze gegevens werk/studeer je bij de Faculteit Sociale Wetenschappen. Controleer of je inderdaad een aanvraag wilt indienen bij de Facultaire Ethische Toetsingscommissie van Geesteswetenschappen.

Als je vermoedt dat er iets niet klopt, neem dan contact op met portalsupport.gw@uu.nl.

**Comment by tymees** [comment]
Awesome, thanks! I'll put it in.

> (and how do we know someone is affiliated to FSW??):

Because we're told what faculty the user belongs to. 

When a user logs in using the new method, we retrieve some data about that user. Solis-id, name, email and the like.

We requested that faculty information is also included in that list. Technically, it's 'department', but that corresponds to faculties. However, UBD would get 'Universitaire Bestuursdient' instead, hence 'department'.
