### ISSUE TITLE
Review all automatic mails

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#529]
The emails in the app have an inconsistent use of formal/informal language (in Dutch) between the emails, as discovered during the review of #528

All emails should be checked and changed if necessary, as it should all be informal per the UU writing styleguide.

**Comment by djhcapel** [comment]
Not sure if it makes sense to mention it here, but I happened to come across a 'short route' message, which contains at least one link that does not lead to the right information (between ** text that should be adapted):

"The FEtC-H has received your application. The automatic screening of the portal has given your **application** the status of short-route research. This means that **we aim to send you** an assessment within two working weeks.

Note: It is possible that your application may still be classified as a 'long-route research', in which case the asssessment procedure may take longer, see the [regulations](https://fetc-gw.wp.hum.uu.nl/en/regulations-fetc-h/) for information. **DELETE: If the latter case, see [section 2.8, p. 14](http://fetc-gw.wp.hum.uu.nl/regulations/) for the possible time paths.
Please be aware of these possibilities and the different time paths involved.**

**Comment by djhcapel** [comment]
I just noticed the Dutch text is okay. The English version should include the text: "Houdt hier a.u.b. rekening mee."
