### ISSUE TITLE
Access chairs, privacy officer and data manager

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#539]
If an application is sent for revision, we often advise the researcher to contact the privacy officer/data manager for advice. These advisory members of the FEtC-H, can, at that point, not be linked to the application anymore (status: revisie noodzakelijk). Is there a way by which they can access all applications without having the secretary role? That would be the easiest solution (from the secretary's point of view), since researchers may also seek advice from p.o. and/or d.m. on their own initiative.

**Comment by djhcapel** [comment]
Actually, this kind of access also applies to both chairs of the FEtC-H.

It should be clear to any of these people which applications they need to assess.

**Comment by miggol** [comment]
Okay, seems like a good idea. Access controls are quite tight as they stand.

Currently, both chairs already have access to both chambers. But they can only see applications that they have been assigned to.

In the future, the desired situation is as follows:
* Select users such as Chairs, PO, and DM should be able to view ALL applications of both chambers.

**Comment by EdoStorm96** [comment]
Make a group that has permissions in combination with a room. Should be able to see everything, yet not edit things. 'kijkrechten'
