### ISSUE TITLE
Blackify the entire repository

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#553]
We've decided to, from some point in the future onwards, commit our code formatted by black. The question remains of when we apply it to the whole back catalog of code.

There's a caveat in that pull requests which are open at time of blackification will be a little harder to merge. Perhaps we can say that once #537 is merged, we take the plunge.

To prevent every affected line referencing this commit in git blame, check out the following: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by tymees** [comment]
It might also be a good idea to add some docs to our meta repo on how to setup IDE's to run black and other tools automatically. I can do that as well
