### ISSUE TITLE
Warning assessments complete

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#563]
Dear colleagues, could the secretary get a warning once assessments have been received by all allocated members? E.g. by the number of applications that is ready after "Nog af te handelen aanvragen" in the menu? 

Nog af te handelen aanvragen [3]

Or by an automatically generated email?

**Comment by tymees** [comment]
Send an automated mail when:
- all decisions have been made

Should just be an `update_go` mod
