### ISSUE TITLE
PermissionDenied error on submitting pre approved proposal

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/ethics#571]
I stumbled upon this bug by accident, but I'm kinda puzzled by why the offending code even exists.

So, in `ProposalSubmitPreApproved` there's an override for `form_valid` method. This method tries to generate a PDF, but it raises an `PermissionDenied` on the `proposal = self.get_object()` call.

This is due to the base base base class using the `UserAllowedMixin`, which will block all calls to `get_object` if the proposal has the submitted state and the user is not a committee member. The override first calls the parent's implementation, which will set the proposal to `submitted`. Thus, the subsequent `get_object` call errors out. 

This problem slipped by us probably because a) we tend not to test pre-approved and 2) because we often test with a secretary level user. 

The puzzling bit is _why_ that override even exists. The parent method does the exact same thing already. I think this is a leftover when the PDF template was decided in the view? But I'm not sure. @miggol you are more familiar with this code, do you concur with my idea?

**Comment by miggol** [comment]
My best guess is that the whole `form_valid` method was copied from `ProposalSubmit` when the new view was added, given that they're very similar. Git blame from 2018 kind of points to this: "Added a new proposal track".

I'll see if it can be removed and submit a different fix otherwise.

**Comment by miggol** [comment]
I wrote a fix, but just figured out a cleaner way of doing things. So it will have to wait until next week

**Comment by EdoStorm96** [comment]
I think #175 is the same issue.
