### ISSUE TITLE
Supervisor and reviewer: no solisid but full name

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#575]
I just noticed that in the 'details' of an application, the solisid is given for the supervisor; could we change this to the full name?

**Comment by djhcapel** [comment]
I also noticed that solisids are used for reviewers on the 'Details' page. Could these also be replaced by names?

**Comment by tymees** [comment]
> I also noticed that solisids are used for reviewers on the 'Details' page. Could these also be replaced by names?

This issue was closed as the original request was fixed (and GH auto-closed because the fix was accepted). 

I've created a new issue for this request: #581
