### ISSUE TITLE
New revisions - add an option to 'Commissieleden aanstellen'

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#583]
An option in case of new revisions is actually missing. Current options are:

 O korte (2-weken) route
 O lange (4-weken) route
 O direct naar revisie

Could the option 'O revisie' be added?

The present regulations do not mention an assessment deadline; do you need one? Then for the time being, used 2 weeks.

**Comment by EdoStorm96** [comment]
Could you further elaborate how the new field would differ from the old field 'O direct naar revisie'?

**Comment by EdoStorm96** [comment]
We can for now just change the text of the short route option, to 'Korte route of revisie' as revisions will usually also take about two weeks. We should also update the text of 'direct naar revisie' to 'Direct terug naar de aanvrager'
