### ISSUE TITLE
Tweaks to Committee Workload Overview

### ISSUE THREAD

**Issue by EdoStorm96** [DH-IT-Portal-Development/ethics#596]
Some requests from @djhcapel:

- Ensure that the committee workload overview is not visible to Chairs and PO's
> * Please adjust format date from month-day-year to day-month-year
> 
> * Please make the default period three months instead of one year

**Comment by djhcapel** [comment]
- It would be appropriate if chairs could see the workload, as well as the secretary.
- Perhaps the text could then read: "Start datum periode (mm-dd-jj):" to help me remind?
- It would be really helpful if the default period could be set to three months, instead of one year.

**Comment by EdoStorm96** [comment]
Ok, I will get to work on this.
