### ISSUE TITLE
Automatically generated mail when revisions are submitted

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#602]
The current automatic mail sent out when a revision is submitted is not accurate. These messages are only applicable for new applications. Can we change the automatic mail for revisions? If so, the text should read:

******
Beste collega,

Je aanmelding is door de FETC-GW ontvangen. Revisies worden in principe door twee leden buiten de vergadering om beoordeeld. 

Namens de FETC-GW, met de vriendelijke groeten,

de FETC-GW secretaris,
Desiree Capel

Dit is een automatisch gegenereerd bericht.
****

BTW: in the long-route mail, it says: "Zeer kort na de vergadering zult u de beoordeling ontvangen." should be "Zeer kort na de vergadering zul je de beoordeling ontvangen."

**Comment by djhcapel** [comment]
And an applicant told me she got a notification in the portal saying that the procedure would take two weeks? What does it say exactly?

**Comment by EdoStorm96** [comment]
> And an applicant told me she got a notification in the portal saying that the procedure would take two weeks? What does it say exactly?

I think it was this mail, which gets sent when an application gets auto-marked as a short route review:

_Beste collega,_

_Je aanmelding is door de FETC-GW ontvangen. De automatische screening van de portal heeft op basis van de door jou gegeven beschrijving voorlopig de status 'korte-route onderzoek' gekregen._

_Dit houdt in dat wij ernaar streven om je binnen twee werkweken een eerste beoordeling van de FETC-GW te sturen._

_NB: Het is mogelijk dat je aanvraag alsnog als 'lange-route onderzoek' wordt aangemerkt, in welk geval de beoordeling langer kan duren, zie het reglement (https://fetc-gw.wp.hum.uu.nl/reglement-fetc-gw/)._ 

Another mention of twee werkweken, features in the mail sent to other applicants, again, for applications which get automarked as a short route.

Ty sent a file containing all emails on 23-11-23. Have a look at that for more info on the emails that get sent to applicants.

**Comment by EdoStorm96** [comment]
Closed as duplicate of #529
