### ISSUE TITLE
Date review round finalized and date 'sent for revision'

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#624]
On the details page, it now says in the left menu: (e.g.) Reviewronde beëindigd op 26 februari 2024, 13:23. 
As far as I understand, this is the date and time of submission of the comments of the last FETC-GW reviewer, not the date the application was sent for revision, so it's a bit confusing. For the secretary, it would be helpful to know when the status of the application was changed to 'in revision', i.e. the application was sent for revision.

Suggestion:

Laatste beoordeling ontvangen op [date, time] _(instead of 'Reviewronde beëindigd op')_
Afhandeling: Revisie noodzakelijk [date, time] _(thus: add date and time of status change)_

Would that be possible?

**Comment by EdoStorm96** [comment]
Note to self: for the latter, we can use `proposal.date_reviewed`
