### ISSUE TITLE
"Applications waiting for conclusion" shows supervisor reviews

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#628]
This is a result of us now closing supervisor reviews when a decision has been made. 

Previously we avoided supervisor reviews getting mixed in with the real deal by never closing them. Now we markg committee reviews explicitly with `Review.is_committee_review`, but this has not been reflected in `ToConcludeReviewApiView`.

We should go over the other API views to see if they don't have the same issue.

Review querysets checked:

- [x] MyDecisionsApiView
- [x] MyOpenDecisions
- [x] OpenDecisions
- [x] OpenSupervisorDecisions
- [x] InRevision
- [x] AllOpenReviews
- [x] AllReviews

**Comment by tymees** [comment]
In addition, we might want to override the status display function to not say 'Approved by FEtC-H' for these reviews, but that's a lower priority than the main issue

**Comment by miggol** [comment]
AllReviews: Deduplication should catch all supervisor reviews. Still can't hurt to filter them out.

AllOpenReviews: Supervisor reviews should already be filtered out by `ASSIGNMENT <= Review.stage <= CLOSING` with `Proposal.status >= Submitted`.

InRevision: Susceptible to this issue, add a filter to `candidates`.
