### ISSUE TITLE
Wilsonbekwame (volwassen) deelnemers

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#671]
This question:

Wilsonbekwaamheid 
Maakt jouw onderzoek gebruik van wilsonbekwame (volwassen) deelnemers?

...only pops up if you tick any of the age groups in the previous question ("Uit welke leeftijdscategorie(ën) bestaat je deelnemersgroep?"). I think this is a bug? The question should always be asked if an age group older than 15 years is ticked.

It should, btw, read: Maakt jouw onderzoek gebruik van wilsonbekwame volwassen deelnemers? (The extra info also mentions adults only).

**Comment by miggol** [comment]
Possible non-issue?

> The question should always be asked if an age group older than 15 years is ticked.

I'm pretty sure this is the current behaviour. Needs clarification on what exactly should be changed.

However, the textual change can be added to 4.0

**Comment by EdoStorm96** [comment]
Currently this only pops up for the age group:
- 16-17
- 18-69
- 70+

Within the portal, we currently say 16 - 17 are adults. Is this not desired?
