### ISSUE TITLE
Figure out table styling for the proposal form.

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/ethics#680]
We need to figure out styling for all the tables in the proposal form. 

Styling for tables in the proposal form can differ from what we use in the review detail tables and such. But preferably we'd have consistent tables everywhere within the proposal form.

_Originally posted by @miggol in https://github.com/DH-IT-Portal-Development/ethics/pull/667#discussion_r1617205278_

**Comment by EdoStorm96** [comment]
I am going to close this, as it should have been closed already.
