### ISSUE TITLE
When not selecting a supervisor, going forward is impossible

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#728]
Path: `/proposals/researcher/`
Occurred during practice application.

When entering an application as a PhD student or as a student, selecting a supervisor is required, but it can be postponed. However, going forward when not having selected a supervisor is not possible at the moment. The page reloads instead.

**Comment by miggol** [comment]
Desiree: This is desired behaviour, we don't want them to continue
