### ISSUE TITLE
"Please specify" remains visible when no longer relevant

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#729]
Path: `/proposals/researcher/`
Occurred during practice application.

When creating an application as a student and selecting "other" in the "what capacity" question, the field "Please specify" appears. If the user then selects "as a postdoc..." or "as a PhD student", this field remains visible. When not entering a value in this field, a validation error is shown.

**Comment by miggol** [comment]
Alright, time to rework the JS logic I guess
