### ISSUE TITLE
No validation error is shown when not entering other researchers

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#730]
Path: /proposals/other_researchers/
Occurred during practice application.

When selecting "yes" but not entering other researchers, no validation error is shown but the user cannot continue.

The same happens when I _do_ add another researcher, but when I also remove myself.

**Comment by tijmenbaarda** [comment]
Probably related to this, when first selecting "yes" and then "no" to the first question, it seems that the (now invisible) researcher list is still evaluated, so the same problem as above occurs.

**Comment by miggol** [comment]
Can be grouped together with #728
