### ISSUE TITLE
Stepper colors not always correct

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#738]
When I start a new application and arrive at _Informatie over de onderzoeker_ the stepper circles are colored in an unexpected way:

First circle Basisgegevens is green (expected)
Next circle Onderzoeker is yellow (expected, current page, no information given yet)
Next circle Andere onderzoekers is green (unexpected, not even seen this page); should be yellow I suppose.
Next circle Financiering is yellow (expected)
Next circle Onderzoeksdoel is yellow (expected)
Next bigger circle WMO is green (unexpected, not even seen this page); should be grey I suppose
Other circles are grey (expected)

Something similar happens if I arrive at _Eén of meerdere trajecten?_:
1. Basisgegevens is yellow (unexpected, every field already filled in); should be green,
2 WMO is green (expected)
3 Trajecten is yellow (expected)
        Traject afronding is yellow (expected)
4 Documenten is grey (expected)
5 Data management is yellow (unexpected); should be grey
6 Indienen is green (unexpected); should be grey

Not sure if this occurs more often, but I'll keep an eye on it. 
Do I need to add other occurrences to this issue?

**Comment by tijmenbaarda** [comment]
In addition, here "Ontwerp" is green but should be yellow (form validation works correctly though):
![image](https://github.com/user-attachments/assets/afbe61ee-bc7e-48d3-b4ca-4c75f0a55a25)
