### ISSUE TITLE
METC - when in doubt or no is chosen, no messages appear

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#739]
Concerns portal 4.0 Ethische toetsing nodig door een Medische Ethische Toetsingscommissie (METC)?

If you choose 'in doubt' in the present portal for either of the two questions, you get a message: "Neem contact op met [Desiree Capel](mailto:fetc-gw@uu.nl) om de twijfels weg te nemen." This does not appear in the 4.0 portal, but it should.

If you choose 'no' in the present portal for either of the two questions, you get a message: "Je onderzoek hoeft niet te worden beoordeeld door de METC." This does not appear in the 4.0 portal, but it should.

If you choose 'yes' for one of the two questions, everything works correctly.

**Comment by miggol** [comment]
Needs to be included in 4.0

Also a JS issue... probably?

Could be bigger than just a textual issue. Good idea to start with this.
