### ISSUE TITLE
Helpt text "Will observations be made in a non-public space?"

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#740]
The help text needs to be adapted: "Bijvoorbeeld er wordt geobserveerd bij iemand thuis, tijdens een hypotheekgesprek, tijdens politieverhoren of **een digitale omgeving** waar een account voor moet worden aangemaakt." Maar ik weet niet of wij dit laatste soort onderzoek wel toetsen. Vraag het na.

**Comment by miggol** [comment]
Small issue, can be included in 4.0
