### ISSUE TITLE
After failing validation of WMO application form, the upload box is visible even if "no" is selected

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#741]
Path: `/proposals/wmo/application/`

See image. The upload box should be invisible, because "no" is selected. When selecting "yes" and then "no" again, the box disappears. Probably not a high priority though.

![image](https://github.com/user-attachments/assets/cd2294a3-a0e1-4c5a-ae6a-96ce5efc88ab)

**Comment by miggol** [comment]
Worth fixing, JS issue, shouldn't be too big. But not high-priority for 4.0
