### ISSUE TITLE
Server error in `studies`

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#745]
Not sure what I did - I was playing with sessions and clicked through as far as I could, and then this server error turned up:

URL: https://fetc.tst.hum.uu.nl/studies/end/26/

Sentry:
https://uu-cdh.sentry.io/issues/11151817/?project=4508008290123856&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0

**Comment by tijmenbaarda** [comment]
Update: this happens in multiple (test) applications and in multiple conditions (interventional, etc.), but it seems to happen only if there are still validation errors in the trajectory.

**Comment by miggol** [comment]
Worth looking into, the sentry log is useful.

**Comment by miggol** [comment]
This appears to be the tenacious `has_intervention` vs. `get_intervention` issue. Interestingly, this one appears to come from a template! `intervention_table` to be precise, with observation and sessions tables suffering from the same.

Requesting this be addressed in #754

**Comment by djhcapel** [comment]
I just started a fresh application and chose 'intervention', which led to a server error. Then I chose 'observation' and again got a server error. Finally, I chose 'task/interviews' and that did work.
