### ISSUE TITLE
Taakonderzoek en interview - textual changes

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#747]
- In Dutch, the following phrases are now being used: 'Taakonderzoek en interview' and 'Het takenonderzoek en/of interviews'. Please consistently use "Taakonderzoek en/of interview(s)".

-In Dutch, please change "Taak: Eén taak of onderdeel van je onderzoek. Bijvoorbeeld: het invullen van een vragenlijst, een interview, of een taaltest." to "Taak: Eén taak of onderdeel van je onderzoek. Bijvoorbeeld: het invullen van een vragenlijst, een interview, of een bepaalde test."

- In English, the following phrases are now being used: "Task-based research and interviews" and "Task-based research and/or interviews". Please consistently use "Task-based research and/or interview(s)".

- In English, please change "Task::A task or procedure within your study. For example: completing an interview, questionnaire, or language test." to "Task: A task or procedure within your study. For example: completing an interview, questionnaire, or a particular test."

**Comment by miggol** [comment]
Included in 4.0

**Comment by miggol** [comment]
Might be nice to include this text at the top of the new/session task form.
