### ISSUE TITLE
System keeps saying that there are errors on trajectory overview page

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#750]
Path: `/studies/end/`

The system keeps saying that there are errors on trajectory overview page, even if everything is filled in there and saved. Both the circle in the stepper remains yellow and an error is indicated on the submission page.

![image](https://github.com/user-attachments/assets/9204d16e-25e2-4885-a810-73d7d909f895)

**Comment by EdoStorm96** [comment]
Yes, this was a stupid bug with this form. It has actually been fixed already in #723. I will deploy the newest version asap.
