### ISSUE TITLE
All 10 additional sets of consent forms are visible from the beginning

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#751]
Path: `/proposals/consent/`

![image](https://github.com/user-attachments/assets/c3b401b8-4c6c-4632-8a22-86c4855e5b71)

The text at the top says that additional sets of forms can be added using a button, but instead all 10 sets of upload fields are visible from the beginning.

**Comment by EdoStorm96** [comment]
This page will dissappear entirely with the new attachments system, that is why it looks so awful ;p. I'll close this issue.
