### ISSUE TITLE
Documents for parents

### ISSUE THREAD

**Issue by djhcapel** [DH-IT-Portal-Development/ethics#759]
See e.g. LC 22-115-04: only children 4 to 11 years old participate. Applicants now have to submit both an information letter ánd parental information. In cases of children < 12 years old, these two documents will always be identical. 

Will or has this been solved in 4.0?

**Comment by miggol** [comment]
Can you elaborate on the desired behaviour? For public interest regardless of age there will only be an info letter. For Consent there will be an info letter, and a consent form either with or without parents present.

**Comment by djhcapel** [comment]
I just tested this in the test environment and it seems to be solved!
