### ISSUE TITLE
Sessions and tasks overview: directly go to task editing page

### ISSUE THREAD

**Issue by tijmenbaarda** [DH-IT-Portal-Development/ethics#775]
Reported by Desiree:

Je kunt nu alleen een sessie bewerken. Is er een reden waarom je niet direct vanuit hier een taak kunt bewerken?

**Comment by EdoStorm96** [comment]
We had initially implemented this ... But we found the overview to then become too overwhelming ... We could still do it though.

**Comment by EdoStorm96** [comment]
Not for 4.0

**Comment by miggol** [comment]
Closed while we evaluate 4.0
